steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image2'
      - '.'
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/image2'
  
  # Additional steps... .
  #Step 4: Deploy the Docker image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/Deployment-1'
      - 'container-1=gcr.io/$PROJECT_ID/image2:latest'
      - '--namespace=namespace-1'

  # Add any additional steps you need for your build process, such as deploying the image to a Kubernetes cluster or running tests.
  
images:
  # Specify the Docker image to be pushed to Google Container Registry
  - 'gcr.io/$PROJECT_ID/image2'
